# Generated by Django 3.2.9 on 2021-11-09 18:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContractNotice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField()),
                ('notice_number', models.CharField(max_length=50)),
                ('tender_name', models.CharField(blank=True, max_length=2083, null=True)),
                ('procedure_state', models.CharField(blank=True, max_length=50, null=True)),
                ('contract_type', models.CharField(blank=True, max_length=50, null=True)),
                ('type_of_procurement', models.CharField(max_length=50)),
                ('estimated_value', models.DecimalField(decimal_places=2, max_digits=19)),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.DeleteModel(
            name='ScrapyItem',
        ),
    ]
